import COLORS from "../src/components";

const SpecArray = [
  {
    text: "Blood Death Knight",
    image: "images/Blood_Death_Knight.webp",

    color: COLORS.deathKnight,
    role: "tank",
    name: "",
    buffs: [
      {
        category: "Agility and Strength",
        name: "Horn of Winter",
        image: "images/Horn_Of_Winter.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Speed Reduction",
        name: "Improved Icy Touch",
        image: "images/Icy_Touch.png",
        link: "https://www.wowhead.com/wotlk/spell=51456/improved-icy-touch",
        spellId: "51456",
      },
      {
        category: "Attack Power %",
        name: "Abomination's Might",
        image: "images/Aboms_Might.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Haste",
        name: "Improved Icy Talons",
        image: "images/Icy_Talons.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Death Grip",
        image: "images/Death_Grip.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hysteria",
        image: "images/Hysteria.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Chains of Ice",
        image: "images/Chains_Of_Ice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Unholy Death Knight",
    image: "images/Unholy_Death_Knight.webp",
    color: COLORS.deathKnight,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Speed Reduction",
        name: "Improved Icy Touch",
        image: "images/Icy_Touch.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Agility and Strength",
        name: "Horn of Winter",
        image: "images/Horn_Of_Winter.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Damage %",
        name: "Ebon Plaguebringer",
        image: "images/Ebon_Plaguebringer.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Disease Damage",
        name: "Crypt Fever",
        image: "images/Crypt_Fever.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Death Grip",
        image: "images/Death_Grip.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Chains of Ice",
        image: "images/Chains_Of_Ice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Frost Death Knight",
    image: "images/Frost_Death_Knight.webp",
    color: COLORS.deathKnight,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Speed Reduction",
        name: "Improved Icy Touch",
        image: "images/Icy_Touch.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Agility and Strength",
        name: "Horn of Winter",
        image: "images/Horn_Of_Winter.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Haste",
        name: "Improved Icy Talons",
        image: "images/Icy_Talons.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Death Grip",
        image: "images/Death_Grip.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Chains of Ice",
        image: "images/Chains_Of_Ice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Balance Druid",
    image: "images/Balance_Druid.webp",
    color: COLORS.druid,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Demoralizing Roar",
        image: "images/Demoralizing_Roar.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Haste %",
        name: "Improved Moonkin Form",
        image: "images/Moonkin_Form.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Crit %",
        name: "Moonkin Form",
        image: "images/Moonkin_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mark of the Wild",
        name: "Mark of the Wild",
        image: "images/Mark_Of_The_Wild.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Damage %",
        name: "Earth and Moon",
        image: "images/Ebon_Plaguebringer.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Hit",
        name: "Improved Faerie Fire",
        image: "images/Faerie_Fire.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Armor Reduction (Minor)",
        name: "Improved Faerie Fire",
        image: "images/Faerie_Fire.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Hit Reduction",
        name: "Insect Swarm",
        image: "images/Insect_Swarm.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Rebirth",
        image: "images/Rebirth.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Innervate",
        image: "images/Innervate.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Typhoon",
        image: "images/Typhoon.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Tranquility",
        image: "images/Tranquility.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Remove Curse",
        image: "images/Remove_Curse.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Cyclone",
        image: "images/Cyclone.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    groupBuffs: [
      {
        name: "Tranquility",
        image: "images/Tranquility.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=48447/tranquility",
        spellId: "48447",
      },
    ],
  },
  {
    text: "Feral Druid",
    image: "images/Feral_Druid.webp",
    color: COLORS.druid,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Speed Reduction",
        name: "Infected Wounds",
        image: "images/Infected_Wounds.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Power Reduction",
        name: "Demoralizing Roar",
        image: "images/Demoralizing_Roar.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Crit",
        name: "Leader of the Pack",
        image: "images/Leader_Of_The_Pack.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Improved Leader of the Pack",
        name: "Improved Leader of the Pack",
        image: "images/Leader_Of_The_Pack.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },

      {
        category: "Armor Reduction (Minor)",
        name: "Faerie Fire",
        image: "images/Faerie_Fire.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mark of the Wild",
        name: "Mark of the Wild",
        image: "images/Mark_Of_The_Wild.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Bleed Damage",
        name: "Mangle",
        image: "images/Mangle.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Rebirth",
        image: "images/Rebirth.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Innervate",
        image: "images/Innervate.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Tranquility",
        image: "images/Tranquility.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Remove Curse",
        image: "images/Remove_Curse.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Cyclone",
        image: "images/Cyclone.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    groupBuffs: [
      {
        name: "Tranquility",
        image: "images/Tranquility.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=48447/tranquility",
        spellId: "48447",
      },
    ],
  },
  {
    text: "Restoration Druid",
    image: "images/Restoration_Druid.webp",
    color: COLORS.druid,
    role: "healer",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Demoralizing Roar",
        image: "images/Demoralizing_Roar.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mark of the Wild",
        name: "Mark of the Wild",
        image: "images/Mark_Of_The_Wild.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Recieved %",
        name: "Tree of Life",
        image: "images/Improved_Tree_Form.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Armor Reduction (Minor)",
        name: "Faerie Fire",
        image: "images/Faerie_Fire.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Rebirth",
        image: "images/Rebirth.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Innervate",
        image: "images/Innervate.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Tranquility",
        image: "images/Tranquility.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Remove Curse",
        image: "images/Remove_Curse.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Cyclone",
        image: "images/Cyclone.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    groupBuffs: [
      {
        name: "Tranquility",
        image: "images/Tranquility.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=48447/tranquility",
        spellId: "48447",
      },
    ],
  },
  {
    text: "Beast Mastery Hunter",
    image: "images/Beast_Mastery_Hunter.webp",
    color: COLORS.hunter,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Damage %",
        name: "Ferocious Inspiration",
        image: "images/Ferocious_Inspiration.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },

      {
        category: "Nature Resistance",
        name: "Aspect of the Wild",
        image: "images/Aspect_Of_The_Wild.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Hit Reduction",
        name: "Scorpid Sting",
        image: "images/Scorpid_Sting.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Reduction",
        name: "Aimed Shot",
        image: "images/Aimed_Shot.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Misdirection",
        image: "images/Misdirection.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Tranquilizing Shot",
        image: "images/Tranquilizing_Shot.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Frost Trap",
        image: "images/Frost_Nova.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Freezing Trap",
        image: "images/Chains_Of_ice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Marksman Hunter",
    image: "images/Marksman_Hunter.webp",
    color: COLORS.hunter,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Power %",
        name: "Trueshot Aura",
        image: "images/Trueshot_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Nature Resistance",
        name: "Aspect of the Wild",
        image: "images/Aspect_Of_The_Wild.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Hit Reduction",
        name: "Scorpid Sting",
        image: "images/Scorpid_Sting.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Reduction",
        name: "Aimed Shot",
        image: "images/Aimed_Shot.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Misdirection",
        image: "images/Misdirection.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Tranquilizing Shot",
        image: "images/Tranquilizing_Shot.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Frost Trap",
        image: "images/Frost_Nova.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Freezing Trap",
        image: "images/Chains_Of_ice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Survival Hunter",
    image: "images/Survival_Hunter.webp",
    color: COLORS.hunter,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Nature Resistance",
        name: "Aspect of the Wild",
        image: "images/Aspect_Of_The_Wild.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Hit Reduction",
        name: "Scorpid Sting",
        image: "images/Scorpid_Sting.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Misdirection",
        image: "images/Misdirection.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Tranquilizing Shot",
        image: "images/Tranquilizing_Shot.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Wyvern Sting",
        image: "images/Wyvern_Sting.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Frost Trap",
        image: "images/Frost_Nova.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Freezing Trap",
        image: "images/Chains_Of_ice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Arcane Mage",
    image: "images/Arcane_Mage.webp",
    color: COLORS.mage,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Damage %",
        name: "Arcane Empowerment",
        image: "images/Arcane_Empowerment.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Intellect",
        name: "Arcane Intellect",
        image: "images/Arcane_Intellect.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Spellsteal",
        image: "images/Spellsteal.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Focus Magic",
        image: "images/Focus_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Remove Curse",
        image: "images/Remove_Curse.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Frost Nova",
        image: "images/Frost_Nova.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Polymorph",
        image: "images/Polymorph.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Fire Mage",
    image: "images/Fire_Mage.webp",
    color: COLORS.mage,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Spell Crit Taken",
        name: "Improved Scorch",
        image: "images/Improved_Scorch.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Intellect",
        name: "Arcane Intellect",
        image: "images/Arcane_Intellect.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Spellsteal",
        image: "images/Spellsteal.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Focus Magic",
        image: "images/Focus_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Remove Curse",
        image: "images/Remove_Curse.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Frost Nova",
        image: "images/Frost_Nova.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Polymorph",
        image: "images/Polymorph.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Frost Mage",
    image: "images/Frost_Mage.webp",
    color: COLORS.mage,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Spell Crit Taken",
        name: "Winter's Chill",
        image: "images/Winters_Chill.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Replenishment",
        name: "Enduring Winter",
        image: "images/Replenishment.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Intellect",
        name: "Arcane Intellect",
        image: "images/Arcane_Intellect.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Spellsteal",
        image: "images/Spellsteal.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Focus Magic",
        image: "images/Focus_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Remove Curse",
        image: "images/Remove_Curse.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Frost Nova",
        image: "images/Frost_Nova.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Polymorph",
        image: "images/Polymorph.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },

  {
    text: "Holy Paladin",
    image: "images/Holy_Paladin.webp",
    color: COLORS.paladin,
    role: "healer",
    name: "",
    buffs: [
      {
        category: "Devotion Aura",
        name: "Devotion Aura",
        image: "images/Devotion_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Power",
        name: "Blessing of Might",
        image: "images/Greater_Blessing_Of_Might.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Mana per 5",
        name: "Blessing of Wisdom",
        image: "images/Greater_Blessing_Of_Wisdom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Stats 10%",
        name: "Blessing of Kings",
        image: "images/Greater_Blessing_Of_Kings.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Health Restore",
        name: "Judgement of Light",
        image: "images/Judgement_Of_Light.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mana Restore",
        name: "Judgement of Wisdom",
        image: "images/Judgement_Of_Wisdom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Fire Resistance",
        name: "Fire Resistance Aura",
        image: "images/Fire_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Frost Resistance",
        name: "Frost Resistance Aura",
        image: "images/Frost_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Shadow Resistance",
        name: "Shadow Resistance Aura",
        image: "images/Shadow_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Magic",
        image: "images/Dispel_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Sacrifice",
        image: "images/Divine_Sacrifice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Sacrifice",
        image: "images/Hand_Of_Sacrifice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Protection",
        image: "images/Hand_Of_Protection.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Freedom",
        image: "images/Hand_Of_Freedom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Aura Mastery",
        image: "images/Aura_Mastery.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Intervention",
        image: "images/Divine_Intervention.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hammer of Justice",
        image: "images/Hammer_Of_Justice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Protection Paladin",
    image: "images/Protection_Paladin.webp",
    color: COLORS.paladin,
    role: "tank",
    name: "",
    buffs: [
      {
        category: "Devotion Aura",
        name: "Devotion Aura",
        image: "images/Devotion_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Power",
        name: "Blessing of Might",
        image: "images/Greater_Blessing_Of_Might.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Mana per 5",
        name: "Blessing of Wisdom",
        image: "images/Greater_Blessing_Of_Wisdom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Stats 10%",
        name: "Blessing of Kings",
        image: "images/Greater_Blessing_Of_Kings.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Damage Reduction %",
        name: "Blessing of Sanctuary",
        image: "images/Greater_Blessing_Of_Sanctuary.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Stats 10%",
        name: "Blessing of Sanctuary*",
        image: "images/Greater_Blessing_Of_Sanctuary.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Crit Strike %",
        name: "Heart of the Crusader",
        image: "images/Heart_Of_The_Crusader.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Recieved %",
        name: "Improved Devotion Aura",
        image: "images/Devotion_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Health Restore",
        name: "Judgement of Light",
        image: "images/Judgement_Of_Light.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mana Restore",
        name: "Judgement of Wisdom",
        image: "images/Judgement_Of_Wisdom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Fire Resistance",
        name: "Fire Resistance Aura",
        image: "images/Fire_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Frost Resistance",
        name: "Frost Resistance Aura",
        image: "images/Frost_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Shadow Resistance",
        name: "Shadow Resistance Aura",
        image: "images/Shadow_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Magic",
        image: "images/Dispel_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Sacrifice",
        image: "images/Divine_Sacrifice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Sacrifice",
        image: "images/Hand_Of_Sacrifice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Protection",
        image: "images/Hand_Of_Protection.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Freedom",
        image: "images/Hand_Of_Freedom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Aura Mastery",
        image: "images/Aura_Mastery.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Intervention",
        image: "images/Divine_Intervention.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hammer of Justice",
        image: "images/Hammer_Of_Justice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Retribution Paladin",
    image: "images/Retribution_Paladin.webp",
    color: COLORS.paladin,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Devotion Aura",
        name: "Devotion Aura",
        image: "images/Devotion_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Power",
        name: "Blessing of Might",
        image: "images/Greater_Blessing_Of_Might.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Mana per 5",
        name: "Blessing of Wisdom",
        image: "images/Greater_Blessing_Of_Wisdom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Stats 10%",
        name: "Blessing of Kings",
        image: "images/Greater_Blessing_Of_Kings.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Crit Strike %",
        name: "Heart of the Crusader",
        image: "images/Heart_Of_The_Crusader.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Damage %",
        name: "Sanctified Retribution",
        image: "images/Sanctified_Retribution.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Replenishment",
        name: "Judgements of the Wise",
        image: "images/Replenishment.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Haste %",
        name: "Swift Retribution",
        image: "images/Swift_Retribution.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Health Restore",
        name: "Judgement of Light",
        image: "images/Judgement_Of_Light.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mana Restore",
        name: "Judgement of Wisdom",
        image: "images/Judgement_Of_Wisdom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Fire Resistance",
        name: "Fire Resistance Aura",
        image: "images/Fire_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Frost Resistance",
        name: "Frost Resistance Aura",
        image: "images/Frost_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Shadow Resistance",
        name: "Shadow Resistance Aura",
        image: "images/Shadow_Resistance_Aura.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Magic",
        image: "images/Dispel_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Sacrifice",
        image: "images/Divine_Sacrifice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Sacrifice",
        image: "images/Hand_Of_Sacrifice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Protection",
        image: "images/Hand_Of_Protection.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hand of Freedom",
        image: "images/Hand_Of_Freedom.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Aura Mastery",
        image: "images/Aura_Mastery.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Intervention",
        image: "images/Divine_Intervention.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hammer of Justice",
        image: "images/Hammer_Of_Justice.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Discipline Priest",
    image: "images/Discipline_Priest.webp",
    color: COLORS.priest,
    role: "healer",
    name: "",
    buffs: [
      {
        category: "Phys Damage Reduction %",
        name: "Inspiration",
        image: "images/Inspiration.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Damage Reduction %",
        name: "Renewed Hope",
        image: "images/Renewed_Hope.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spirit",
        name: "Divine Spirit",
        image: "images/Divine_Spirit.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Stamina",
        name: "Power Word: Fortitude",
        image: "images/Power_Word_Fortitude.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Shadow Resistance",
        name: "Shadow Protection",
        image: "images/Prayer_Of_Shadow_Resistance.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Magic",
        image: "images/Dispel_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mass Dispel",
        image: "images/Mass_Dispel.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hymn of Hope",
        image: "images/Hymn_Of_Hope.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Hymn",
        image: "images/Divine_Hymn.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Pain Suppression",
        image: "images/Pain_Suppression.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mind Control",
        image: "images/Mind_Control.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Power Infusion",
        image: "images/Power_Infusion.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Psychic Scream",
        image: "images/Psychic_Scream.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Holy Priest",
    image: "images/Holy_Priest.webp",
    color: COLORS.priest,
    role: "healer",
    name: "",
    buffs: [
      {
        category: "Reduced Phys Damage Taken",
        name: "Inspiration",
        image: "images/Inspiration.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spirit",
        name: "Divine Spirit",
        image: "images/Divine_Spirit.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Stamina",
        name: "Power Word: Fortitude",
        image: "images/Power_Word_Fortitude.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Shadow Resistance",
        name: "Shadow Protection",
        image: "images/Prayer_Of_Shadow_Resistance.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Magic",
        image: "images/Dispel_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mass Dispel",
        image: "images/Mass_Dispel.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hymn of Hope",
        image: "images/Hymn_Of_Hope.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Hymn",
        image: "images/Divine_Hymn.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Guardian Spirit",
        image: "images/Holy_Priest.webp",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mind Control",
        image: "images/Mind_Control.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Psychic Scream",
        image: "images/Psychic_Scream.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Shadow Priest",
    image: "images/Shadow_Priest.webp",
    color: COLORS.priest,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Spell Hit",
        name: "Misery",
        image: "images/Misery.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spirit",
        name: "Divine Spirit",
        image: "images/Divine_Spirit.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Replenishment",
        name: "Vampiric Touch",
        image: "images/Replenishment.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Stamina",
        name: "Power Word: Fortitude",
        image: "images/Power_Word_Fortitude.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Shadow Resistance",
        name: "Shadow Protection",
        image: "images/Prayer_Of_Shadow_Resistance.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Magic",
        image: "images/Dispel_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mass Dispel",
        image: "images/Mass_Dispel.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hymn of Hope",
        image: "images/Hymn_Of_Hope.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Divine Hymn",
        image: "images/Divine_Hymn.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mind Control",
        image: "images/Mind_Control.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Psychic Scream",
        image: "images/Psychic_Scream.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    groupBuffs: [
      {
        name: "Vampiric Embrace",
        image: "images/Vampiric_Embrace.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=15286/vampiric-embrace",
        spellId: "15286",
      },
    ],
  },
  {
    text: "Assassination Rogue",
    image: "images/Assassination_Rogue.webp",
    color: COLORS.rogue,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Armor Reduction (Major)",
        name: "Expose Armor",
        image: "images/Expose_Armor.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Crit Strike %",
        name: "Master Poisoner",
        image: "images/Master_Poisoner.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Reduction",
        name: "Wound Poison",
        image: "images/Wound_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Tricks of the Trade",
        image: "images/Tricks_Of_The_Trade.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Anesthetic Poison",
        image: "images/Anesthetic_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mind-numbing Poison",
        image: "images/Crypt_Fever.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Blind",
        image: "images/Blind.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dismantle",
        image: "images/Dismantle.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Combat Rogue",
    image: "images/Combat_Rogue.webp",
    color: COLORS.rogue,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Armor Reduction (Major)",
        name: "Expose Armor",
        image: "images/Expose_Armor.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Phys Vulnerability",
        name: "Savage Combat",
        image: "images/Savage_Combat.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Reduction",
        name: "Wound Poison",
        image: "images/Wound_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Tricks of the Trade",
        image: "images/Tricks_Of_The_Trade.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Anesthetic Poison",
        image: "images/Anesthetic_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mind-numbing Poison",
        image: "images/Crypt_Fever.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Blind",
        image: "images/Blind.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dismantle",
        image: "images/Dismantle.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Subtlety Rogue",
    image: "images/Subtlety_Rogue.webp",
    color: COLORS.rogue,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Armor Reduction (Major)",
        name: "Expose Armor",
        image: "images/Expose_Armor.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Reduction",
        name: "Wound Poison",
        image: "images/Wound_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Tricks of the Trade",
        image: "images/Tricks_Of_The_Trade.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Anesthetic Poison",
        image: "images/Anesthetic_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mind-numbing Poison",
        image: "images/Crypt_Fever.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Blind",
        image: "images/Blind.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dismantle",
        image: "images/Dismantle.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },

  {
    text: "Elemental Shaman",
    image: "images/Elemental_Shaman.webp",
    color: COLORS.shaman,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Stoneskin Totem",
        name: "Stoneskin Totem",
        image: "images/Stoneskin_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Agility and Strength",
        name: "Strength of Earth Totem",
        image: "images/Strength_Of_Earth_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Bloodlust/Heroism",
        name: "Bloodlust/Heroism",
        image: "images/Bloodlust.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mana per 5",
        name: "Mana Spring Totem",
        image: "images/Mana_Spring_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Crit %",
        name: "Elemental Oath",
        image: "images/Elemental_Oath.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Haste",
        name: "Wrath of Air Totem",
        image: "images/Wrath_Of_Air_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Power",
        name: "Totem of Wrath",
        image: "images/Totem_Of_Wrath.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Crit Strike %",
        name: "Totem of Wrath",
        image: "images/Totem_Of_Wrath.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Haste",
        name: "Windfury Totem ",
        image: "images/Windfury.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Fire Resistance",
        name: "Fire Resistance Totem",
        image: "images/Fire_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Frost Resistance",
        name: "Frost Resistance Totem",
        image: "images/Frost_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Nature Resistance",
        name: "Nature Resistance Totem",
        image: "images/Nature_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Cleansing Totem",
        image: "images/Cleansing_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Bloodlust/Heroism",
        image: "images/Bloodlust.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hex",
        image: "images/Hex.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Purge",
        image: "images/Purge.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    groupBuffs: [
      {
        name: "Healing Stream Totem",
        image: "images/Healing_Stream_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=58757/healing-stream-totem",
        spellId: "58757",
      },
      {
        name: "Cleansing Totem",
        image: "images/Cleansing_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=8170/cleansing-totem",
        spellId: "8170",
      },
      {
        name: "Tremor Totem",
        image: "images/Tremor_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=8143/tremor-totem",
        spellId: "8143",
      },
    ],
  },
  {
    text: "Enhancement Shaman",
    image: "images/Enhancement_Shaman.webp",
    color: COLORS.shaman,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Stoneskin Totem",
        name: "Stoneskin Totem",
        image: "images/Stoneskin_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Agility and Strength",
        name: "Strength of Earth Totem",
        image: "images/Strength_Of_Earth_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Bloodlust/Heroism",
        name: "Bloodlust/Heroism",
        image: "images/Bloodlust.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mana per 5",
        name: "Mana Spring Totem",
        image: "images/Mana_Spring_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Power %",
        name: "Unleashed Rage",
        image: "images/Unleashed_Rage.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Haste",
        name: "Wrath of Air Totem",
        image: "images/Wrath_Of_Air_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Power",
        name: "Flametongue Totem",
        image: "images/Flametongue_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Haste",
        name: "Improved Windfury Totem ",
        image: "images/Windfury.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Fire Resistance",
        name: "Fire Resistance Totem",
        image: "images/Fire_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Frost Resistance",
        name: "Frost Resistance Totem",
        image: "images/Frost_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Nature Resistance",
        name: "Nature Resistance Totem",
        image: "images/Nature_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Cleansing Totem",
        image: "images/Cleansing_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Bloodlust/Heroism",
        image: "images/Bloodlust.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hex",
        image: "images/Hex.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Purge",
        image: "images/Purge.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    groupBuffs: [
      {
        name: "Healing Stream Totem",
        image: "images/Healing_Stream_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=58757/healing-stream-totem",
        spellId: "58757",
      },
      {
        name: "Cleansing Totem",
        image: "images/Cleansing_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=8170/cleansing-totem",
        spellId: "8170",
      },
      {
        name: "Tremor Totem",
        image: "images/Tremor_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=8143/tremor-totem",
        spellId: "8143",
      },
    ],
  },
  {
    text: "Restoration Shaman",
    image: "images/Restoration_Shaman.webp",
    color: COLORS.shaman,
    role: "healer",
    name: "",
    buffs: [
      {
        category: "Stoneskin Totem",
        name: "Stoneskin Totem",
        image: "images/Stoneskin_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Agility and Strength",
        name: "Strength of Earth Totem",
        image: "images/Strength_Of_Earth_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Bloodlust/Heroism",
        name: "Bloodlust/Heroism",
        image: "images/Bloodlust.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Mana per 5",
        name: "Mana Spring Totem",
        image: "images/Mana_Spring_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Power",
        name: "Flametongue Totem",
        image: "images/Flametongue_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Haste",
        name: "Wrath of Air Totem",
        image: "images/Wrath_Of_Air_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Reduced Phys Damage Taken",
        name: "Ancestral Healing",
        image: "images/Ancestral_Healing.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Haste",
        name: "Windfury Totem ",
        image: "images/Windfury.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Fire Resistance",
        name: "Fire Resistance Totem",
        image: "images/Fire_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Frost Resistance",
        name: "Frost Resistance Totem",
        image: "images/Frost_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Nature Resistance",
        name: "Nature Resistance Totem",
        image: "images/Nature_Resistance_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Remove Curse",
        image: "images/Remove_Curse.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Disease",
        image: "images/Dispel_Disease.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Dispel Poison",
        image: "images/Dispel_Poison.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Cleansing Totem",
        image: "images/Cleansing_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Mana Tide Totem",
        image: "images/Mana_Tide_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Bloodlust/Heroism",
        image: "images/Bloodlust.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Hex",
        image: "images/Hex.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Purge",
        image: "images/Purge.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    groupBuffs: [
      {
        name: "Healing Stream Totem",
        image: "images/Healing_Stream_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=58757/healing-stream-totem",
        spellId: "58757",
      },
      {
        name: "Cleansing Totem",
        image: "images/Cleansing_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=8170/cleansing-totem",
        spellId: "8170",
      },
      {
        name: "Tremor Totem",
        image: "images/Tremor_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=8143/tremor-totem",
        spellId: "8143",
      },
      {
        name: "Mana Tide Totem",
        image: "images/Mana_Tide_Totem.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        link: "https://www.wowhead.com/wotlk/spell=16190/mana-tide-totem",
        spellId: "16190",
      },
    ],
  },
  {
    text: "Arms Warrior",
    image: "images/Arms_Warrior.webp",
    color: COLORS.warrior,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Demoralizing Shout",
        image: "images/Demoralizing_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Power",
        name: "Battle Shout",
        image: "images/Battle_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Health",
        name: "Commanding Shout",
        image: "images/Commanding_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Armor Reduction (Major)",
        name: "Sunder Armor",
        image: "images/Sunder_Armor.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Phys Vulnerability",
        name: "Blood Frenzy",
        image: "images/Blood_Frenzy.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Bleed Damage",
        name: "Trauma",
        image: "images/Trauma.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Speed Reduction",
        name: "Thunderclap",
        image: "images/Thunderclap.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Reduction",
        name: "Mortal Strike",
        image: "images/Mortal_Strike.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Shattering Throw",
        image: "images/Shattering_Throw.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Intimidating Shout",
        image: "images/Intimidating_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Disarm",
        image: "images/Disarm.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Fury Warrior",
    image: "images/Fury_Warrior.webp",
    color: COLORS.warrior,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Demoralizing Shout",
        image: "images/Demoralizing_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },

      {
        category: "Attack Power",
        name: "Battle Shout",
        image: "images/Battle_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Health",
        name: "Commanding Shout",
        image: "images/Commanding_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Armor Reduction (Major)",
        name: "Sunder Armor",
        image: "images/Sunder_Armor.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Melee Crit",
        name: "Rampage",
        image: "images/Rampage.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Speed Reduction",
        name: "Thunderclap",
        image: "images/Thunderclap.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Healing Reduction",
        name: "Mortal Strike",
        image: "images/Mortal_Strike.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Shattering Throw",
        image: "images/Shattering_Throw.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Intimidating Shout",
        image: "images/Intimidating_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Disarm",
        image: "images/Disarm.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },

  {
    text: "Protection Warrior",
    image: "images/Protection_Warrior.webp",
    color: COLORS.warrior,
    role: "tank",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Demoralizing Shout",
        image: "images/Demoralizing_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Power",
        name: "Battle Shout",
        image: "images/Battle_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Health",
        name: "Commanding Shout",
        image: "images/Commanding_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
        checked: true,
      },
      {
        category: "Armor Reduction (Major)",
        name: "Sunder Armor",
        image: "images/Sunder_Armor.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Attack Speed Reduction",
        name: "Improved Thunderclap",
        image: "images/Thunderclap.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Interrupt",
        image: "images/Kick.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Vigilance",
        image: "images/Vigilance.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Shattering Throw",
        image: "images/Shattering_Throw.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Intimidating Shout",
        image: "images/Intimidating_Shout.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Disarm",
        image: "images/Disarm.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Affliction Warlock",
    image: "images/Affliction_Warlock.webp",
    color: COLORS.warlock,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Curse of Weakness",
        image: "images/Curse_Of_Weakness.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Intellect",
        name: "Fel Intelligence",
        image: "images/Fel_Intelligence.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spirit",
        name: "Fel Intelligence",
        image: "images/Fel_Intelligence.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Armor Reduction (Minor)",
        name: "Curse of Weakness",
        image: "images/Curse_Of_Weakness.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Crit Taken",
        name: "Improved Shadow Bolt",
        image: "images/Shadow_Bolt.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Damage %",
        name: "Curse of the Elements",
        image: "images/Curse_Of_The_Elements.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Felhunter's Devour Magic",
        image: "images/Devour_Magic.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Fear",
        image: "images/Fear.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Create Soulstone",
        image: "images/Create_Soulstone.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Demonology Warlock",
    image: "images/Demonology_Warlock.webp",
    color: COLORS.warlock,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Curse of Weakness",
        image: "images/Curse_Of_Weakness.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Power",
        name: "Demonic Pact",
        image: "images/Demonic_Pact.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Damage %",
        name: "Curse of the Elements",
        image: "images/Curse_Of_The_Elements.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Armor Reduction (Minor)",
        name: "Curse of Weakness",
        image: "images/Curse_Of_Weakness.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Crit Taken",
        name: "Improved Shadow Bolt",
        image: "images/Shadow_Bolt.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Fear",
        image: "images/Fear.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Create Soulstone",
        image: "images/Create_Soulstone.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
  {
    text: "Destruction Warlock",
    image: "images/Destruction_Warlock.webp",
    color: COLORS.warlock,
    role: "dps",
    name: "",
    buffs: [
      {
        category: "Attack Power Reduction",
        name: "Curse of Weakness",
        image: "images/Curse_Of_Weakness.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Health",
        name: "Improved Imp",
        image: "images/Blood_Pact.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Spell Damage %",
        name: "Curse of the Elements",
        image: "images/Curse_Of_The_Elements.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Armor Reduction (Minor)",
        name: "Curse of Weakness",
        image: "images/Curse_Of_Weakness.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        category: "Replenishment",
        name: "Improved Soul Leech",
        image: "images/Replenishment.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
    utility: [
      {
        name: "Fear",
        image: "images/Fear.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
      {
        name: "Create Soulstone",
        image: "images/Create_Soulstone.png",
        link: "https://www.wowhead.com/wotlk/spell=57330/horn-of-winter",
        spellId: "57330",
      },
    ],
  },
];

export default SpecArray;
