const SpecList = () =>  
[
  {
    id:1,
    text:"Blood Death Knight",
    image:require('./images/dk_blood.png').default,
    color:'red',
    buffs:'',
  },
  {    
    id:2,
    text:"Unholy Death Knight",
    image:require('./images/dk_unholy.png').default,
    color:'red',
    buffs:'',
  },
  {
    id:3,
    text:"Frost Death Knight",
    image:require('./images/dk_frost.png').default,
    color:'red',
    buffs:'',
  },
  {    
    id:4,
    text:"Balance Druid",
    image:require('./images/druid_balance.png').default,
    color:'orange',
    buffs:'',
  },
  {    
    id:5,
    text:"Feral Druid",
    image:require('./images/druid_feral.png').default,
    color:'orange',
    buffs:'',
  },
  {    
    id:6,
    text:"Restoration Druid",
    image:require('./images/druid_restoration.png').default,
    color:'orange',
    buffs:'',
  },
  {
    id:7,
    text:"Beast Mastery Hunter",
    image:require('./images/hunter_beastmastery.png').default,
    color:'green',
    buffs:'',
  },
  {
    id:8,
    text:"Marksman Hunter",
    image:require('./images/hunter_marksman.png').default,
    color:'green',
    buffs:'',
  },
  {
    id:9,
    text:"Survival Hunter",
    image:require('./images/hunter_survival.png').default,
    color:'green',
    buffs:'',
  },
  {    
    id:10,
    text:"Arcane Mage",
    image:require('./images/mage_arcane.png').default,
    color:'teal',
    buffs:'',
  },
  {
    id:11,
    text:"Fire Mage",
    image:require('./images/mage_fire.png').default,
    color:'teal',
    buffs:'',
  },
  {    
    id:12,
    text:"Frost Mage",
    image:require('./images/mage_frost.png').default,
    color:'teal',
    buffs:'',
  },
  {
    id:13,
    text:"Holy Paladin",
    image:require('./images/paladin_holy.png').default,
    color:'pink',
    buffs:'',
  },
  {
    id:14,
    text:"Protection Paladin",
    image:require('./images/paladin_protection.png').default,
    color:'pink',
    buffs:'',
  },
  {
    id:15,
    text:"Retribution Paladin",
    image:require('./images/paladin_retribution.png').default,
    color:'pink',
    buffs:'',
  },
  {
    id:16,
    text:"Discipline Priest",
    image:require('./images/priest_discipline.png').default,
    color:'white',
    buffs:'',
  },
  {
    id:17,
    text:"Holy Priest",
    image:require('./images/priest_holy.png').default,
    color:'white',
    buffs:'',
  },
  {
    id:18,
    text:"Shadow Priest",
    image:require('./images/priest_shadow.png').default,
    color:'white',
    buffs:'',
  },
  {
    id:19,
    text:"Assassination Rogue",
    image:require('./images/rogue_assassination.png').default,
    color:'yellow',
    buffs:'',
  },
  {
    id:20,
    text:"Combat Rogue",
    image:require('./images/rogue_combat.png').default,
    color:'yellow',
    buffs:'',
  },
  {
    id:21,
    text:"Subtlety Rogue",
    image:require('./images/rogue_subtlety.png').default,
    color:'yellow',
    buffs:'',
  },

  {
    id:22,
    text:"Elemental Shaman",
    image:require('./images/shaman_elemental.png').default,
    color:'blue',
    buffs:'',
  },
  {
    id:23,
    text:"Enhancement Shaman",
    image:require('./images/shaman_enhancement.png').default,
    color:'blue',
    buffs:'',
  },
  {
    id:24,
    text:"Restoration Shaman",
    image:require('./images/shaman_restoration.png').default,
    color:'blue',
    buffs:'',
  },
  {
    id:25,
    text:"Arms Warrior",
    image:require('./images/warrior_arms.png').default,
    color:'brown',
    buffs:'',
  },
  {
    id:26,
    text:"Fury Warrior",
    image:require('./images/warrior_fury.png').default,
    color:'brown',
    buffs:'',
  },
  {
    id:27,
    text:"Protection Warrior",
    image:require('./images/warrior_protection.png').default,
    color:'brown',
    buffs:'',
  },
  {
    id:28,
    text:"Affliction Warlock",
    image:require('./images/warlock_affliction.png').default,
    color:'purple',
    buffs:'',
  },
  {
    id:29,
    text:"Demonology Warlock",
    image:require('./images/warlock_demonology.png').default,
    color:'purple',
    buffs:'',
  },
  {
    id:30,
    text:"Destruction Warlock",
    image:require('./images/warlock_destruction.png').default,
    color:'purple',
    buffs:'',
  },
]


export default SpecList
